var MENU =
{
    vn: {
        app: "thilaixe.de",
        app_name: "HỌC LÁI XE TIẾNG VIỆT - HẠNG B - ",
        version_free: "BẢN MIỄN PHÍ",
        version_full: "BẢN ĐẦY ĐỦ",
        klass: "Hạng B",
        question: "Câu hỏi",
        test: "Thi thử",
        test_klass: "Thi thử hạng B",
        search: "Tìm kiếm",
        statistic: "Thống kê",
        setting: "Cài đặt",
        buy_pro: "Nâng cấp",
        license: "Bản quyền",
        all_question: "Toàn bộ câu hỏi",
        answered: "Câu hỏi đã trả lời",
        answered_right: "Câu trả lời đúng",
        answered_wrong: "Câu trả lời sai",
        hard_question: "Câu hỏi khó",
        not_answered: "Câu hỏi chưa trả lời",
        number_question: "Câu hỏi về số",
        variant_question: "Câu hỏi biến thể",
        film_question: "Câu hỏi video",
        weaknesses: "Yếu điểm",
        back: "Quay lại",
        basic_divider: "Bộ câu hỏi sắp xếp theo chủ đề: Cơ bản",
        advanced_divider: "Bộ câu hỏi sắp xếp theo chủ đề: Nâng cao",
        search_question: "Tìm câu hỏi",
        close: "Đóng",
        delete_result: "Xóa kết quả",        
        result_question: "Kết quả câu hỏi",
        result_test: "Kết quả thi thử",
        answer: "Câu trả lời",
        answer_yes: "Trả lời đúng",
        answer_no: "Trả lời sai",
        not_answer: "Chưa trả lời",
        question_b: "Câu hỏi hạng B",
        //cài đặt
        screen_start: "Màn hình khi mở ứng dụng",
        start: "Bắt đầu",
        rate_app: "Đánh giá ứng dụng",
        down_result: "Tải kết quả",
        setting_question: "Cài đặt câu hỏi",        
        random: "ngẫu nhiên",
        audio: "Âm thanh",
        down_film: "Tải video",
        quality_low: "Độ phân giải thấp",
        down_all_film: "Tải toàn bộ video",
        quality_up: "Độ phân giải cao",
        change_all_question: "Thay đổi bộ câu hỏi",
        question_prev: "Bộ câu hỏi trước",
        online_learning: "Dành cho người học Online",
        open_online: "Mở hệ thống học Online",
        send_resutl: "Gửi kết quả",
        question_advanced: "Nâng cao B",
        code_question: "Mã câu hỏi: ",
        point: "Điểm: ",
        cancel: "Hủy",
        view_result: "Trả lời",
        previos_question: "Câu trước",
        next_question: "Câu tiếp",
        ticked: "Đánh dấu",
        submit: "Nộp bài",
        back_check: "Bạn có thực sự muốn dừng bài thi thử này?",
        submit_check: "Bạn có thực sự muốn hoàn thành bài thi thử này?",
        alert_submit: "Bạn đang có ",
        alert_submit_1: " câu hỏi chưa được trả lời",
        show_question: "Nếu bạn chuyển sang phần câu hỏi của câu này bạn sẽ không thể xem lại Video này nữa. Bạn có thực sự muốn chuyển sang phần câu hỏi luôn không?",
        yes: "Có",
        no: "Không",
        start_video: "Hãy xem đoạn video về tình huống giao thông sau đây.",
        button_start_video: "Bắt đầu video",
        view_question_video: "Xem câu hỏi",
        title_count_play1: "Bạn có thể xem video ",
        title_count_play2: " lần.",
        count_ticked_1: "Còn lại ",
        count_ticked_2: " câu",
        result_title: "Kết quả",
        back_test: "Thi lại",
        point_error: "Điểm sai",
        basic_test: "Cơ bản",
        advanced: "Hạng B Nâng cao",
        not_bestanden: "Không đỗ",
        bestanden: "Thi đỗ",
        hasmade: "Đã làm",
        wrong_point: "Điểm sai",
        advanced_question: "Câu hỏi nâng cao",
        basic_question: "Câu hỏi cơ bản",
        all_rick: "Đúng tất cả",
        your_answer: "Câu trả lời của bạn",
        right_answer: "Câu trả lời đúng",
        status_answer_right: "Bạn đã trả lời chính xác!",
        status_answer_wrong: "Bạn đã trả lời sai!",
        status_answer_hard: "Câu hỏi này đã được đánh dấu khó.",
        status_answer_un_hard: "Câu hỏi này đã được bỏ đánh dấu khó",
        version: "Phiên bản",
        licence: "Bản quyền",
        activated: "Bạn đã active thành công và có thể dùng bản đầy đủ!",
        question_from: "Bộ câu hỏi từ 01.04.2016",
        no_test: "Chưa có kết quả thi thử",
        buy_full_version: "Bạn có muốn đăng nhập để dùng bản đầy đủ không?",
        buy_full_test: "Bạn có muốn đăng nhập để có nhiều bài thi không?",
        cause_tion: "Chú ý",
        go: "Đến câu: ",
        hard: "Khó"
    },
    de: {
        app_name: "FÜHRERSCHEIN FAHRSCHULE KLASSE B ",
        version_free: "DEMO VERSION",
        version_full: "VOLLVERSION",
        klass: "Klasse B",
        question: "Fragen lernen",
        test: "Prüfungssimulation",
        test_klass: "Prüfungssimulationen für Klasse B",
        search: "Fragen suchen",
        statistic: "Meine Statistik",
        setting: "Einstellungen",
        buy_pro: "Upgrade",
        license: "Bản quyền",
        all_question: "Alle Fragen",
        answered: "Bearbeitete",
        answered_right: "Richtig beantwortete",
        answered_wrong: "Falsch beantwortete",
        hard_question: "Schwierige",
        not_answered: "Noch nicht gemachte",
        number_question: "Zahlenfragen",
        variant_question: "Variationen",
        film_question: "Filmfragen",
        weaknesses: "Meine Schwächen",
        back: "Zurück",
        basic_divider: "AMTLICHER FRAGENKATALOG NACH THEMEN SORTIERT: GRUNDSTOFF",
        advanced_divider: "AMTLICHER FRAGENKATALOG NACH THEMEN SORTIERT: ZUSATZSTOFF",
        search_question: "Frage suchen",
        close: "Schließen",
        delete_result: "Ergebnisse löschen",
        result_question: "Ergebnisse der Fragen",
        result_test: "Ergebnisse der Prüfungssimulationen",
        answer: "Antworten",
        answer_yes: "Richtig beantwortete",
        answer_no: "Falsch beantwortete",
        not_answer: "Noch nicht gemachte",
        hard_question_stastic: "Schwierige Fragen",
        question_b: "Fragen für Klass B",
        //cài đặt
        screen_start: "STARTBILDSCHIRM DER ANWENDUNG",
        start: "Start",
        rate_app: "AppLaiXe bewerten",
        down_result: "Tải kết quả",
        setting_question: "EINSTELLUNGEN BEIM „FRAGEN LERNEN“",
        question_setting: "Fragen ",
        random: "zufällig",
        audio: "Ton",
        down_film: "Tải video",
        quality_low: "Độ phân giải thấp",
        down_all_film: "Tải toàn bộ video",
        quality_up: "Độ phân giải cao",
        change_all_question: "HIER KÖNNEN SIE DEN FRAGENKATALOG ÄNDERN",
        question_prev: "Fragenkatalog gültig ab",
        online_learning: "Dành cho người học Online",
        open_online: "Mở hệ thống học Online",
        send_resutl: "Gửi kết quả",
        question_advanced: "Zusatzfrage B",
        code_question: "Frage: ",
        point: "Punkte: ",
        cancel: "Abbrechen",
        view_result: "Antwort",
        previos_question: "Zurück",
        next_question: "Weiter",
        ticked: "Markieren",
        submit: "Abgabe",
        submit_check: "Möchten Sie diese Prüfung wirklich beenden?",
        back_check: "Möchten Sie diese Prüfung wirklich abbrechen?",
        show_question: "Wenn Sie zur Aufgabenstellung wechseln, können Sie den Film nicht noch einmal ansehen! Wollen Sie wirklich zur Aufgabenstellung wechseln?",
        alert_submit: "Sie haben noch ",
        alert_submit_1: " nicht beantwortete Fragen",
        yes: "Ja",
        no: "Nein",
        start_video: "Bitte starten Sie den Film, um sich mit der Situation vertraut zu machen.",
        button_start_video: "Film starten",
        view_question_video: "Zur Aufgabenstellung",
        title_count_play1: "Sie können the sich den Film insgesamt ",
        title_count_play2: " mal ansehen.",
        count_ticked_1: "noch ",
        count_ticked_2: " aufgaben",
        result_title: "Ihre Ergebnisse",
        back_test: "Wiederholen",
        point_error: "Fehlerpunkte",
        basic_test: "Grundstoff",
        advanced: "Zusatzstoff Klasse B",
        not_bestanden: "Nicht bestanden",
        bestanden: "Bestanden",
        hasmade: "Gemacht",
        wrong_point: "Fehlerpunkte",
        advanced_question: "Zusatzfragen",
        basic_question: "Grundfragen",
        all_rick: "Alles richtig",
        your_answer: "Ihre Antwort",
        right_answer: "Richtige Antwort",
        status_answer_right: "Sie haben richtig geantwortet!",
        status_answer_wrong: "Sie haben falsch geantwortet!",
        status_answer_hard: "Die Frage wurde als schwierig markiert.",
        status_answer_un_hard: "Die Frage wurde als nicht schwierig markiert.",
        version: "Version",
        licence: "Alle Rechte vorbehalten",
        question_from: "Fragenkatalog gültig ab 01.04.2016",
        no_test: "Es gibt keine Ergebnisse der Prüfungssimulationen",
        cause_tion: "Aufmerksamkeit",
        go: "Gehe zu: ",
        hard: "Schwer"
    }
};